version: "3"
services:
  app:
    build:
      context: .
    environment:
      - OLD_DATABASE_URL=postgres://old:hehehe@0.0.0.0:5432/old
      - NEW_DATABASE_URL=postgres://new:hahaha@0.0.0.0:5433/new
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app/
      - /node_modules
    command: yarn start
